


POST   https://urban-capybara-x6q656wj4jrhvx7g-8080.app.github.dev/api/dresseur
Content-Type: application/json

{
  "name": "test",
  "age": 5,
  "level": 5,
  "pokemons": [
    {
      "name": "tesname",
      "attribute": "FEU",
      "power": 5
    }
  ]
}



GET https://urban-capybara-x6q656wj4jrhvx7g-8080.app.github.dev/api/dresseur/1
GET https://urban-capybara-x6q656wj4jrhvx7g-8080.app.github.dev/api/pokemons/tesname
